spring:
  datasource:
    url: jdbc:mysql://dailybaekjoon.cinppxid5rbv.ap-northeast-2.rds.amazonaws.com:3306/dailybaekjoon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootdailybaekjoon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true # sql? ??? ???? true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      open-in-view: false